name: pr

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.19
      - name: Earthly version
        run: earthly --version
      - name: Run build
        env:
          EARTHLY_BUILD_ARGS: "COMMIT_HASH,VERSION"
          COMMIT_HASH: ${{ github.sha }}
          VERSION: "0.0.0-pr"
          FORCE_COLOR: 1
        run: |
          earthly --no-cache +all
